mode: dev
prod:
  - botname: StatsBot
    username: sextafeirafutebolbot
    token: 
      7875219149:AAEp8kmi0gPDgXop3QTxUlLO3IFq-bmv4bA
    about:
      "this is some short text about my bot"
    description:
      "This is a description of what my bot can do which customer will use"

dev:
  - botname: StatsBot
    username: sextafeirafutebolbot
    token: 
      7875219149:AAEp8kmi0gPDgXop3QTxUlLO3IFq-bmv4bA
    about:
      "this is some short text about development bot  "
    description:
      "This is a description of what my development bot can do with testing"
